"""Central path configuration for the VeriFace pipeline.

Every path used to be recomputed independently in each notebook as
``ROOT = Path.cwd().parent`` — fragile, since it silently depended on which
directory the notebook happened to be launched from. This module gives every
script/module in the project one shared, overridable source of truth.

Override the root via the ``VERIFACE_ROOT`` environment variable if running
from outside a checkout of this repository (e.g. a mounted data volume in
Docker). All other paths are derived from it and can also be overridden
individually if your layout differs from the default.
"""

from __future__ import annotations

import os
from pathlib import Path

# Repo root: two levels up from this file (src/config.py -> repo root).
_DEFAULT_ROOT = Path(__file__).resolve().parents[1]
ROOT = Path(os.environ.get("VERIFACE_ROOT", _DEFAULT_ROOT)).resolve()


def _env_path(var_name: str, default: Path) -> Path:
    value = os.environ.get(var_name)
    return Path(value).resolve() if value else default


# Raw, dataset-provided face-only video folders (see HANDOFF.md "Dataset
# Required" for exact expected sub-folder names — these come from the
# original notebooks and were never independently verified against a real
# dataset in this environment).
DATASET_DIR = _env_path("VERIFACE_DATASET_DIR", ROOT / "Dataset")

# Generated by src/data/build_splits.py
DATA_DIR = _env_path("VERIFACE_DATA_DIR", ROOT / "data")
LABELS_JSON = DATA_DIR / "labels.json"
TRAIN_SPLIT_FILE = DATA_DIR / "train.txt"
VAL_SPLIT_FILE = DATA_DIR / "val.txt"
TEST_SPLIT_FILE = DATA_DIR / "test_internal.txt"
RESERVED_SPLIT_FILE = DATA_DIR / "reserved_200.txt"
DATA_MANIFEST_FILE = DATA_DIR / "data_manifest.yaml"

# Generated by src/data/extract_frames.py
FRAMES_DIR = _env_path("VERIFACE_FRAMES_DIR", ROOT / "preprocessed" / "frames")

# Frames sampled per video during training-data preparation. Mirrors
# src/data/extract_frames.py's own FRAMES_PER_VIDEO_DEFAULT (kept as a
# separate local constant there, unchanged, to avoid touching that module) —
# this is the shared value new code (src/data/preprocess_raw.py) reads from,
# so a future change only has one place to update for new pipeline stages.
FRAMES_PER_VIDEO = 8

# Generated by src/data/extract_embeddings.py
EMBEDDINGS_DIR = _env_path("VERIFACE_EMBEDDINGS_DIR", ROOT / "embeddings")

# Model checkpoints (all training outputs)
CHECKPOINT_DIR = _env_path("VERIFACE_CHECKPOINT_DIR", ROOT / "checkpoints")
SPATIAL_CHECKPOINT_DIR = CHECKPOINT_DIR / "spatial"
TEMPORAL_CHECKPOINT_DIR = CHECKPOINT_DIR / "temporal"
ENSEMBLE_CHECKPOINT_DIR = CHECKPOINT_DIR / "ensemble"

SPATIAL_BEST_CHECKPOINT = SPATIAL_CHECKPOINT_DIR / "spatial_best_valAUC.pth"
TEMPORAL_BEST_CHECKPOINT = TEMPORAL_CHECKPOINT_DIR / "temporal_best_valAUC.pth"

# Logs
LOG_DIR = _env_path("VERIFACE_LOG_DIR", ROOT / "logs")

# Results / metrics that are populated only once real hardware has run
# src/eval/benchmark.py and a held-out evaluation. See results/README.md.
# Deliberately does NOT exist yet in this environment — see HANDOFF.md.
RESULTS_DIR = _env_path("VERIFACE_RESULTS_DIR", ROOT / "results")
METRICS_FILE = RESULTS_DIR / "metrics.json"

SPLITS = ("train", "val", "test")
